pool:
  vmImage: 'Ubuntu-20.04'

trigger:
  tags:
    include:
      - "*"
  branches:
    include:
      - refs/heads/*

pr:
  branches:
    include:
      - '*'

variables:
  # Variables imported from brewblox group:
  # CTL_SAS_TOKEN
  - group: brewblox

steps:
- task: UsePythonVersion@0
  inputs:
    addToPath: true
    versionSpec: '3.6'
    architecture: 'x64'

- bash: |
    pip install poetry
    poetry install
  displayName: Install

- bash: |
    BRANCH=$(echo $(Build.SourceBranch) | grep -oP "^refs/heads/\K.*")
    TAG=$(echo $BRANCH | tr '/' '-' | tr '[:upper:]' '[:lower:]')
    VERSION=$(poetry version --no-ansi | cut -d " " -f2)
    echo "##vso[task.setvariable variable=BRANCH]$BRANCH"
    echo "##vso[task.setvariable variable=TAG]$TAG"
    echo "##vso[task.setvariable variable=VERSION]$VERSION"
  displayName: Export build variables

- bash: poetry run pytest
  displayName: Test

- bash: |
    poetry build -f sdist
  displayName: Build

- bash: >-
    az storage blob upload
    --account-name brewblox
    --container-name ctl
    --sas-token '$(CTL_SAS_TOKEN)'
    --name "brewblox-ctl-$(TAG).tar.gz"
    --file "./dist/brewblox-ctl-$(VERSION).tar.gz"
  displayName: Upload to Azure Storage
  condition: and(succeeded(), variables.BRANCH)
