defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
        certFile = "/config/brewblox.crt"
        keyFile = "/config/brewblox.key"

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "brewblox.local"
watch = true
